apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Database.DNS }}
spec:
  selector:
    app: {{ .Values.Database.DNS }}
  type: ClusterIP
  ports:
  - protocol: TCP
    name: {{ .Values.Database.DNS }}
    port: {{ .Values.Database.Port }}
    targetPort: {{ .Values.Database.Port }}
