apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.Database.DNS }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.Database.DNS }}
  serviceName: {{ .Values.Database.DNS }}
  replicas: {{ .Values.Database.Replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.Database.DNS }}
    spec:
      containers:
      - name: {{ .Values.Database.DNS }}
        {{- $image_version := .Values.Database.Container.Image.Version | toString }}
        image: {{ printf "%s/%s:%s" .Values.Database.Container.Repository .Values.Database.Container.Image.Name $image_version }}
        envFrom:
        - secretRef:
            name: db-credentials
        ports:
        - containerPort: {{ .Values.Database.Port }}
        volumeMounts:
        - name: {{ .Values.Database.DNS }}
          mountPath: {{ .Values.Database.Volume.Mount_Path }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.Database.DNS }}
    spec:
      accessModes: [ {{ .Values.Database.Volume.Access_Mode }} ]
      resources:
        requests:
          storage: {{ .Values.Database.Volume.Minimum_Storage }}
