apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Web.DNS }}
  labels:
    app: {{ .Values.Web.DNS }}
spec:
  replicas: {{ .Values.Web.Replicas }}
  selector:
    matchLabels:
      app: {{ .Values.Web.DNS }}
  template:
    metadata:
      labels:
        app: {{ .Values.Web.DNS }}
    spec:
      containers:
      - name: {{ .Values.Web.DNS }}
        {{- $image_version := .Chart.AppVersion | toString }}
        image: {{ printf "%s/%s:%s" .Values.Web.Container.Repository .Values.Web.Container.Image.Name $image_version }}
        env:
        - name: DB_SERVER
          value: {{ .Values.Database.DNS }}
        ports:
        - containerPort: {{ .Values.Web.Port }}
